name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Check code formatting
        run: ./gradlew spotlessCheck --stacktrace

      - name: Run lint checks
        run: ./gradlew lintDebug --stacktrace

      - name: Build project
        run: ./gradlew build --stacktrace

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: |
            **/build/reports
            **/build/outputs
